name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install pytest pytest-homeassistant-custom-component sdnotify
      - name: Run tests
        run: |
          pytest tests/ -v
